services:
  db:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      REDIS_URL: redis://db
    depends_on:
      - db    
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  
  
